### PR TITLE
Make Transit Gateway support PCA accounts

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##
This PR adds the newly-created PCA accounts to the list of those accounts that are allowed to access our Transit Gateway.

Additionally, this PR adds a new role (`ProvisionPrivateDNSRecords`) that allows the provisioning of DNS records in the private zone in the Shared Services account.

## 💭 Motivation and Context ##
Without this, the PCA accounts would not be able to be included in the COOL network.  The `ProvisionPrivateDNSRecords` role will be used to create private DNS records for Con-PCA.

This change is part of https://github.com/cisagov/cool-system/issues/82.

## 🧪 Testing ##
I applied this change in the Shared Services (Staging) environment and verified that the expected Transit Gateway resources were created for the PCA (Staging) account.

Further testing will be conducted with @zenine07 to confirm that the Staging PCA account is able to successfully route traffic through the Transit Gateway.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
This all looks correct to me.  Powerful work!

**Review by hillaryj — APPROVED** [review]
🎆

**Comment by dav3r** [comment]
This PR should not be merged until @zenine07 confirms that the Staging PCA account is able to successfully route traffic through the Staging Transit Gateway.  

After this PR is merged, I will apply these changes to the Production environment

**Review by mcdonnnj — APPROVED** [review]
🚀 :shipit:

**Review by jsf9k — APPROVED** [review]
I still approve!

**Comment by dav3r** [comment]
I updated the "Description" block at the top of this PR to reflect the recent commits, then re-requested reviews from @hillaryj and @mcdonnnj (thanks @jsf9k for re-reviewing already).

**Review by hillaryj — APPROVED** [review]
🎉

**Pull request merged**
